### PR TITLE
macOS setup script added

### PR DESCRIPTION
**Pull request by mt-shihab26**
I am in mac. So, I added the setup script for macOS

### CODE REVIEW

**Comment by Joystick1479** [comment]
Hey p-nerd, 

I can't get this to run. Could you help? I am getting the error:

Setup-macOS.sh: line 3: ./Vendor/Binaries/Premake/macOS/premake5: No such file or directory

**Comment by p-nerd** [comment]
You have to run  `./Scripts/Setup-macOS.sh` on root of the project. Sorry I forgot to mention.

**Comment by p-nerd** [comment]
Screenshot 2023-11-20 at 11 41 55 PM

**Comment by banna12345bob** [comment]
Hey p-nerd

Why don't you just have the script `pushd ..` and then `popd` instead of forcing the user to run in the root folder? You would have to run `cd $(dirname $0)` before running changing the directory command though.

**Comment by mt-shihab26** [comment]
@banna12345bob I was more comfortable with the approach.  But for project consistency I update with this approach. Thank you for you suggestions.

**Pull request closed without merging**
